In [1]:
#!pip install theano
#!pip install tensorflow
#!pip install keras

In [2]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r"D:\ANN-Udemy\P16-Artificial-Neural-Networks\Artificial_Neural_Networks\Churn_Modelling.csv")

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x = data.iloc[:,1:-1]
x.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619    France  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
2    15619304      Onio          502    France  Female   42       8   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0       0.00              1          1               1        101348.88  
1   83807.86              1          0               1        112542.58  
2  159660.80              3          1               0        113931.57  
3       0.00              2          0               0         93826.63  
4  125510.82              1          1               1         79084.10

In [6]:
y = data[["Exited"]]

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [8]:
x.drop("Surname",axis=1,inplace=True)

In [9]:
le = LabelEncoder()


In [10]:
x["Gender"] = le.fit_transform(x["Gender"])

In [11]:
x["Geography"] = le.fit_transform(x["Geography"])

In [12]:
new_Geography = pd.get_dummies(x["Geography"],prefix="Geo",drop_first=True)

In [13]:
x = pd.concat([x,new_Geography],axis=1)
x.drop("Geography",axis=1,inplace=True)

In [14]:
x[["Balance","EstimatedSalary"]] = x[["Balance","EstimatedSalary"]].astype(int)

In [15]:
x.head()

CustomerId  CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  \
0    15634602          619       0   42       2        0              1   
1    15647311          608       0   41       1    83807              1   
2    15619304          502       0   42       8   159660              3   
3    15701354          699       0   39       1        0              2   
4    15737888          850       0   43       2   125510              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Geo_1  Geo_2  
0          1               1           101348      0      0  
1          0               1           112542      0      1  
2          1               0           113931      0      0  
3          0               0            93826      0      0  
4          1               1            79084      0      1

In [16]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=0)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((8000, 12), (2000, 12), (8000, 1), (2000, 1))

# Scale the data

In [17]:
sc = StandardScaler().fit(X_train)
sc_X_train = sc.transform(X_train)
sc_X_test = sc.transform(X_test)
sc_X_train

array([[-0.20216686,  0.16958176, -1.09168714, ...,  1.10642907,
        -0.5698444 ,  1.74309049],
       [ 0.80704397, -2.30455945,  0.91601335, ..., -0.74865592,
         1.75486502, -0.57369368],
       [-1.51908128, -1.19119591, -1.09168714, ...,  1.48532999,
        -0.5698444 , -0.57369368],
       ...,
       [-1.63233785,  0.9015152 ,  0.91601335, ...,  1.41231335,
        -0.5698444 , -0.57369368],
       [-0.38173152, -0.62420521, -1.09168714, ...,  0.84432697,
        -0.5698444 ,  1.74309049],
       [-1.37508365, -0.28401079, -1.09168714, ...,  0.32472867,
         1.75486502, -0.57369368]])

In [18]:
sc_X_train = pd.DataFrame(sc_X_train, columns = X_train.columns)
sc_X_test = pd.DataFrame(sc_X_test, columns = X_test.columns)

In [19]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [21]:
classifiers = Sequential()

In [35]:
classifiers.add(Dense(output_dim=6,input_dim=12,init="uniform",activation="relu"))
classifiers.add(Dense(output_dim=6,init="uniform",activation="relu"))
classifiers.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))
classifiers.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [53]:
classifiers.fit(sc_X_train,Y_train,nb_epoch=60,batch_size=10)

Epoch 1/60
8000/8000 [==============================] - 2s 233us/step - loss: 0.4031 - acc: 0.8332
Epoch 2/60
8000/8000 [==============================] - 2s 234us/step - loss: 0.4028 - acc: 0.8346
Epoch 3/60
8000/8000 [==============================] - 2s 234us/step - loss: 0.4026 - acc: 0.8356
Epoch 4/60
8000/8000 [==============================] - 2s 236us/step - loss: 0.4018 - acc: 0.8352
Epoch 5/60
8000/8000 [==============================] - 2s 237us/step - loss: 0.4013 - acc: 0.8356
Epoch 6/60
8000/8000 [==============================] - 2s 237us/step - loss: 0.4014 - acc: 0.8364
Epoch 7/60
8000/8000 [==============================] - 2s 238us/step - loss: 0.4017 - acc: 0.8352
Epoch 8/60
8000/8000 [==============================] - 2s 238us/step - loss: 0.4007 - acc: 0.8351
Epoch 9/60
8000/8000 [==============================] - 2s 235us/step - loss: 0.4008 - acc: 0.8369
Epoch 10/60
8000/8000 [==============================] - 2s 232us/step - loss: 0.4010 - acc: 0.8364
Epoch 11/

In [37]:
y_pred = classifiers.predict(sc_X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,Y_test)

array([[1552,  280],
       [  43,  125]], dtype=int64)

### Use our ANN model to predict if the customer with the following informations will leave the bank:
* Geography: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: $60000
Number of Products: 2
* Does this customer have a credit card ? Yes
Is this customer an Active Member: Yes
Estimated Salary: $50000

In [48]:
demo = pd.DataFrame(pd.Series({"CustomerId":15402455,"CreditScore":600,"Gender":1,"Age":40,"Tenure":3,"Balance":60000,\
              "NumOfProducts":2,"HasCrCard":1,"IsActiveMember":1,"EstimatedSalary":50000,"Geo_1":0,"Geo_2":1})).T
demo

CustomerId  CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  \
0    15402455          600       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Geo_1  Geo_2  
0          1               1            50000      0      1

In [49]:
demo_X_train = sc.transform(demo)
demo_X_train

array([[-4.03021086, -0.52111599,  0.91601335,  0.10961719, -0.68538967,
        -0.25690156,  0.8095029 ,  0.64259497,  0.9687384 , -0.87202466,
        -0.5698444 ,  1.74309049]])

In [56]:
pred = classifiers.predict(demo_X_train)
print(pred>0.5)

[[False]]


# Evaluationg ANN using K-Fold Cross Validation

In [22]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.layers import Dropout

In [23]:
def build_classifier():
    classifiers = Sequential()
    classifiers.add(Dense(output_dim=6,input_dim=12,init="uniform",activation="relu"))
    classifiers.add(Dropout(p=0.1))# add in case of overfitting
    classifiers.add(Dense(output_dim=6,init="uniform",activation="relu"))
    classifiers.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))
    classifiers.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
    return classifiers

In [24]:
classifiers = KerasClassifier(build_fn=build_classifier,nb_epoch=60,batch_size=10)
accuracy = cross_val_score(estimator=classifiers,X = sc_X_train,y = Y_train,cv=10,n_jobs=-1)

In [25]:
accuracy.mean()

0.7959999969601632

In [26]:
accuracy.std()

0.010105690620981692

# Improving the accuracy by tuning parameters

In [ ]:
# It will take little time
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV
from keras.layers import Dropout

# function for the cross validation and the gridsearch
def build_classifier(opt):
    classifiers = Sequential()
    classifiers.add(Dense(output_dim=6,input_dim=12,init="uniform",activation="relu"))
    classifiers.add(Dropout(p=0.1))# add in case of overfitting
    classifiers.add(Dense(output_dim=6,init="uniform",activation="relu"))
    classifiers.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))
    classifiers.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])
    return classifiers

classifiers = KerasClassifier(build_fn=build_classifier)
parameters = {"nb_epoch":[20,25,32],"batch_size":[100,400,500],"opt":["adam","rmsprop"]}
grid_search = GridSearchCV(estimator=classifiers,param_grid=parameters,scoring="accuracy",cv=10)
grid_search.fit(sc_X_train,Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
print("best parameters:",best_parameters)
print("best accuracy:",best_accuracy)

# ==========================================================